//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Spa_EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Services
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Не указано имя услуги")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина имени")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Не указана цена услуги")]
        [Range(1, 5000, ErrorMessage = "Недопустимая цена")]
        public double Price { get; set; }
        [Required(ErrorMessage = "Не указана длительность услуги")]
        [Range(1, 300, ErrorMessage = "Недопустимая длительность")]
        public int Duration { get; set; }
        public int IdCat { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
