//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Spa_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaServicesContainer : DbContext
    {
        //public SpaServicesContainer()
        //    : base("name=SpaServicesContainer")
        //{
        //}

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        //public virtual DbSet<Category> CategorySet { get; set; }
        //public virtual DbSet<Services> ServicesSet { get; set; }
        //public virtual DbSet<Purchase> PurchaseSet { get; set; }
    }
}
